# Generated by Django 4.1 on 2022-09-01 00:51

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "descricao",
                    models.CharField(default="Descrição do POST", max_length=1024),
                ),
                ("texto", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
    ]
