# Generated by Django 4.1.1 on 2023-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("victech", "0003_postagem_table_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="Sem Classificação",
                        max_length=256,
                        null=True,
                        verbose_name="Categoria",
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_department",
                    models.CharField(
                        blank=True,
                        default="Sem Classificação",
                        max_length=256,
                        null=True,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        to="victech.category", verbose_name="Categorias"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="postagem",
            name="category",
            field=models.ManyToManyField(
                blank=True, null=True, to="victech.category", verbose_name="Categoria"
            ),
        ),
    ]
