# Generated by Django 4.1.1 on 2023-08-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("victech", "0004_category_department_postagem_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postagem",
            options={"ordering": ["-data_criacao"]},
        ),
    ]
