# Generated by Django 3.2.15 on 2023-09-14 15:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victech', '0005_alter_postagem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideias', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
