# Generated by Django 3.2.15 on 2023-09-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victech', '0006_ideias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideias',
            options={'verbose_name': 'Ideia', 'verbose_name_plural': 'Ideias'},
        ),
        migrations.AddField(
            model_name='ideias',
            name='titulo',
            field=models.CharField(default='Ideia', max_length=200),
        ),
    ]
