# Generated by Django 3.2.15 on 2023-09-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victech', '0007_auto_20230914_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Cor'),
        ),
    ]
