# Generated by Django 3.2.25 on 2024-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victech', '0008_category_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUserBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('number_of_requests', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de requisições')),
                ('last_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Última página visualizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('last_access_at', models.DateTimeField(auto_now=True, verbose_name='Última visita')),
            ],
            options={
                'verbose_name': 'Relatório de visitas do Blog',
                'verbose_name_plural': 'Relatório de visitas do Blog',
                'unique_together': {('address',)},
            },
        ),
    ]
