# Generated by Django 3.2.25 on 2024-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('victech', '0009_reportuserblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuserblog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhes do acesso'),
        ),
    ]
