# Generated by Django 4.1.1 on 2022-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titulo do projeto"),
                ),
                ("image", models.ImageField(upload_to="projects/")),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do projeto"
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
