# Generated by Django 3.2.15 on 2022-10-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link_project',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link do projeto'),
        ),
    ]
