# Generated by Django 3.2.15 on 2022-10-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_projects_link_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255, verbose_name='Instituição')),
                ('course', models.CharField(max_length=255, verbose_name='Curso')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
